services:
  db:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_evaluation_form
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: local-server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: local-client
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
